import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className=" bg-amber-100 text-black">
      <body className={`antialiased bg-amber-100 text-black`}>{children}</body>
    </html>
  );
}
